/*-----------------------------------------------------------------				
					BASE DE DATOS - escuela - GRUPO 4

	-Crear una base de datos HSQL Embedded
	-Contamos con 7 tablas
	-IMPORTANTE: para la creación de la clave primaria autoincremental es necesario añadir el siguiente código:
			GENERATED BY DEFAULT AS IDENTITY
			
			Ej: ID_ESCUELA INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY
			El ID no va a reconocer GENERATED, pero lo ejecuta igualmente
	
-------------------------------------------------------------------*/



--Datos-creación tabla ESCUELA
/*ESCUELA
ID_ESCUELA	INTEGER		NOT NULL	PRIMARY KEY	
NOMBRE		VARCHAR 	NOT NULL	
DIRECCION	VARCHAR		NOT NULL*/


--Creación tabla ALUMNO
/*ALUMNO
ID_ALUMNO 	INTEGER		NOT NULL	PRIMARY KEY
NOMBRE		VARCHAR 	NOT NULL
APELLIDO	VARCHAR 	NOT NULL
CIUDAD		VARCHAR 	NOT NULL
FECHA_NACIMIENTO	DATE 	NOT NULL
FECHA_GRADUACION	DATE 	NOT NULL
**/


--Datos-creación  tabla CURSO
/*CURSO
ID_CURSO 	INTEGER		NOT NULL	PRIMARY KEY
ID_ESCUELA	refecncia 	ESCUELA
NOMBRE		VARCHAR 	NOT NULL
FECHA_INICIO	DATE 	NOT NULL
FECHA_FIN		DATE 	NOT NULL
**/


--Datos-creación  tabla CURSO_ASIGNATURA
/*CURSO_ASIGNATURA
 ID_CURSO_ASIGNATURA 	INTEGER		NOT NULL	PRIMARY KEY
 ID_CURSO		refecncia 	CURSO
 ID_ASIGNATURA	refecncia 	ASIGNATURA
 */

--Datos-creación  tabla AULA
/*AULA
ID_AULA		INTEGER		NOT NULL	PRIMARY KEY
ID_CURSO	refecncia 	CURSO
NOMBRE		VARCHAR 	NOT NULL
*/
 

--Datos-creación  tabla ASIGNATURA
/*ASIGNATURA
ID_ASIGNATURA 	INTEGER		NOT NULL	PRIMARY KEY
ID_CURSO		refecncia 	CURSO
ID_PROFESOR		refecncia 	PROFESOR
NOMBRE			VARCHAR 	NOT NULL
*/
 

--Datos-creación  tabla PROFESOR
/*PROFESOR
ID_PROFESOR 	INTEGER		NOT NULL	PRIMARY KEY
NOMBRE			VARCHAR 	NOT NULL
FECHA_NACIMIENTO	DATE 	NOT NULL
FECHA_MUERTE		DATE
*/


--Datos tabla ESCUELA
INSERT INTO PUBLIC.PUBLIC.ESCUELA (NOMBRE, DIRECCION) VALUES 
	('Escuela Primaria A Solaina', 'Rúa dos Carballos 123, A Coruña, Galicia'), 
	('Instituto Secundario As Mariñas', 'Avenida de Galicia 456, Lugo, Galicia'),
	('Bachillerato O Castro', 'Paseo de los Olmos 789, Vigo, Galicia');


--Datos tabla CURSOS
INSERT INTO PUBLIC.PUBLIC.CURSO (ID_ESCUELA, NOMBRE, FECHA_INICIO, FECHA_FIN) VALUES 
	(0, 'PRIMERO_PRIMARIA', '2018-09-11', '2018-06-22'),
	(0, 'SEGUNDO_PRIMARIA', '2018-09-11', '2018-06-22'),
	(0, 'TERCERO_PRIMARIA', '2018-09-11', '2018-06-22'),
	(0, 'CUARTO_PRIMARIA', '2018-09-11', '2018-06-22'),
	(0, 'QUINTO_PRIMARIA', '2018-09-11', '2018-06-22'),
	(0, 'SEXTO_PRIMARIA', '2018-09-11', '2018-06-22'),
	(1, 'PRIMERO_SECUNDARIA', '2018-09-20', '2018-06-30'),
	(1, 'SEGUNDO_SECUNDARIA', '2018-09-20', '2018-06-30'),
	(1, 'TERCERO_SECUNDARIA', '2018-09-20', '2018-06-30'),
	(1, 'CUARTO_SECUNDARIA', '2018-09-20', '2018-06-30'),
	(2, 'PRIMERO_BACHILLER', '2018-09-20', '2018-06-30'),
	(2, 'SEGUNDO_BACHILLER', '2018-09-20', '2018-05-20')
;


--Datos tabla AULA
INSERT INTO PUBLIC.PUBLIC.AULA (ID_CURSO, NOMBRE) VALUES 
	(0, 'A'),
	(0, 'B'),
	(1, 'A'),
	(1, 'B'),
	(2, 'A'),
	(2, 'B'),
	(3, 'A'),
	(3, 'B'),
	(4, 'A'),
	(4, 'B'),
	(5, 'A'),
	(5, 'B'),
	(6, 'A'),
	(6, 'B'),
	(7, 'A'),
	(7, 'B'),
	(8, 'A'),
	(8, 'B'),
	(9, 'A'),
	(9, 'B'),
	(10, 'A'),
	(10, 'B'),
	(11, 'A'),
	(11, 'B'),
	(11, 'A')
;
	

--Datos tabla ALUMNO
INSERT INTO PUBLIC.PUBLIC.ALUMNO (ID_CURSO, NOMBRE, CIUDAD, FECHA_NACIMIENTO, FECHA_GRADUACION)
VALUES
    (0, 'Alba Fernández', 'A Coruña', '2017-04-12', NULL),
    (0, 'Hugo Rodríguez', 'Santiago', '2017-06-05', NULL),
    (0, 'Lucía López', 'Lugo', '2017-02-19', NULL),
    (0, 'Leo Pérez', 'Ourense', '2017-08-25', NULL),
    (0, 'Noa Gómez', 'Pontevedra', '2017-11-30', NULL),
    (0, 'Iago Martínez', 'Ferrol', '2017-03-07', NULL),
    (0, 'Sabela Castro', 'Betanzos', '2017-09-14', NULL),
    (0, 'Mateo Torres', 'Ribeira', '2017-01-28', NULL),
    (0, 'Carla Álvarez', 'Vilagarcía', '2017-05-22', NULL),
    (0, 'Xoel Fernández', 'A Coruña', '2017-10-16', NULL),
    (0, 'Nerea González', 'Santiago', '2017-12-09', NULL),
    (0, 'Antón López', 'Lugo', '2017-07-03', NULL),
    (0, 'Aroa Romero', 'Ourense', '2017-02-25', NULL),
    (0, 'Brais Pereira', 'Pontevedra', '2017-11-18', NULL),
    (0, 'Iria Martínez', 'Ferrol', '2017-04-30', NULL),
    (0, 'Xiana Díaz', 'Betanzos', '2017-06-20', NULL),
    (0, 'David González', 'Ribeira', '2017-08-12', NULL),
    (0, 'Inés López', 'Vilagarcía', '2017-03-15', NULL),
    (0, 'Marcos Salgado', 'A Coruña', '2017-05-05', NULL),
    (0, 'Santi Castro', 'Santiago', '2017-10-02', NULL),
    (1, 'Mateo Fernández', 'A Coruña', '2016-04-12', NULL),
    (1, 'Carla Rodríguez', 'Santiago', '2016-06-05', NULL),
    (1, 'Noa López', 'Lugo', '2016-02-19', NULL),
    (1, 'Leo Pérez', 'Ourense', '2016-08-25', NULL),
    (1, 'Alba Gómez', 'Pontevedra', '2016-11-30', NULL),
    (1, 'Iago Martínez', 'Ferrol', '2016-03-07', NULL),
    (1, 'Sabela Castro', 'Betanzos', '2016-09-14', NULL),
    (1, 'Hugo Torres', 'Ribeira', '2016-01-28', NULL),
    (1, 'Inés Álvarez', 'Vilagarcía', '2016-05-22', NULL),
    (1, 'David Fernández', 'A Coruña', '2016-10-16', NULL),
    (1, 'Antía González', 'Santiago', '2016-12-09', NULL),
    (1, 'Xoel López', 'Lugo', '2016-07-03', NULL),
    (1, 'Aroa Romero', 'Ourense', '2016-02-25', NULL),
    (1, 'Brais Pereira', 'Pontevedra', '2016-11-18', NULL),
    (1, 'Xiana Martínez', 'Ferrol', '2016-04-30', NULL),
    (1, 'Iria Díaz', 'Betanzos', '2016-06-20', NULL),
    (1, 'Marcos González', 'Ribeira', '2016-08-12', NULL),
    (1, 'Lucía Salgado', 'Vilagarcía', '2016-03-15', NULL),
    (1, 'Santi Castro', 'A Coruña', '2016-05-05', NULL),
    (1, 'Mateo Álvarez', 'Santiago', '2016-10-02', NULL),
    (1, 'Valeria Fernández', 'Ourense', '2016-12-22', NULL),
    (3, 'Pablo Fernández', 'A Coruña', '2015-04-10', NULL),
    (3, 'Sara Rodríguez', 'Santiago', '2015-05-15', NULL),
    (3, 'Miguel López', 'Lugo', '2015-01-20', NULL),
    (3, 'Emma Pérez', 'Ourense', '2015-06-30', NULL),
    (3, 'David Gómez', 'Pontevedra', '2015-11-05', NULL),
    (3, 'Paula Martínez', 'Ferrol', '2015-03-25', NULL),
    (3, 'Xoán Castro', 'Betanzos', '2015-08-18', NULL),
    (3, 'Lucía Torres', 'Ribeira', '2015-02-14', NULL),
    (3, 'Martín Álvarez', 'Vilagarcía', '2015-09-22', NULL),
    (3, 'Aitana Fernández', 'A Coruña', '2015-12-11', NULL),
    (3, 'Antón González', 'Santiago', '2015-07-04', NULL),
    (3, 'Iria López', 'Lugo', '2015-10-19', NULL),
    (3, 'Adrián Romero', 'Ourense', '2015-01-30', NULL),
    (3, 'Valeria Pereira', 'Pontevedra', '2015-06-02', NULL),
    (3, 'Hugo Martínez', 'Ferrol', '2015-03-09', NULL),
    (3, 'Lara Díaz', 'Betanzos', '2015-05-25', NULL),
    (3, 'Dani González', 'Ribeira', '2015-08-07', NULL),
    (3, 'Carla Salgado', 'Vilagarcía', '2015-04-20', NULL),
    (3, 'Santi Castro', 'A Coruña', '2015-11-15', NULL),
    (3, 'Paula Álvarez', 'Santiago', '2015-02-22', NULL),
    (3, 'Martín Fernández', 'Ourense', '2015-09-01', NULL),
    (4, 'Ana Fernández', 'A Coruña', '2014-04-01', NULL),
    (4, 'Dani Rodríguez', 'Santiago', '2014-05-12', NULL),
    (4, 'Javi López', 'Lugo', '2014-01-18', NULL),
    (4, 'Alba Pérez', 'Ourense', '2014-06-21', NULL),
    (4, 'Hugo Gómez', 'Pontevedra', '2014-11-02', NULL),
    (4, 'Noa Martínez', 'Ferrol', '2014-03-27', NULL),
    (4, 'Mía Castro', 'Betanzos', '2014-09-09', NULL),
    (4, 'Leo Torres', 'Ribeira', '2014-02-16', NULL),
    (4, 'Sara Álvarez', 'Vilagarcía', '2014-07-30', NULL),
    (4, 'Martín Fernández', 'A Coruña', '2014-10-20', NULL),
    (4, 'Paula González', 'Santiago', '2014-12-11', NULL),
    (4, 'Iago López', 'Lugo', '2014-08-03', NULL),
    (4, 'Antía Romero', 'Ourense', '2014-01-25', NULL),
    (4, 'Brais Pereira', 'Pontevedra', '2014-06-10', NULL),
    (4, 'Carla Martínez', 'Ferrol', '2014-04-15', NULL),
    (4, 'Xiana Díaz', 'Betanzos', '2014-11-28', NULL),
    (4, 'Marcos González', 'Ribeira', '2014-09-19', NULL),
    (4, 'Valeria Salgado', 'Vilagarcía', '2014-03-08', NULL),
    (4, 'Santi Castro', 'A Coruña', '2014-02-28', NULL),
    (4, 'Mateo Álvarez', 'Santiago', '2014-12-22', NULL),
    (5, 'Laura Fernández', 'A Coruña', '2013-04-12', '2018-06-22'),
    (5, 'Nico Rodríguez', 'Santiago', '2013-05-07', '2018-06-22'),
    (5, 'Dani López', 'Lugo', '2013-02-02', '2018-06-22'),
    (5, 'Alba Pérez', 'Ourense', '2013-08-10', '2018-06-22'),
    (5, 'Noa Gómez', 'Pontevedra', '2013-11-11', '2018-06-22'),
    (5, 'Martín Martínez', 'Ferrol', '2013-01-01', '2018-06-22'),
    (5, 'Carla Castro', 'Betanzos', '2013-09-20', '2018-06-22'),
    (5, 'Sara Torres', 'Ribeira', '2013-03-05', '2018-06-22'),
    (5, 'Xoel Álvarez', 'Vilagarcía', '2013-12-15', '2018-06-22'),
    (5, 'Antía Fernández', 'A Coruña', '2013-10-20', '2018-06-22'),
    (5, 'Iago González', 'Santiago', '2013-06-17', '2018-06-22'),
    (5, 'Aroa López', 'Lugo', '2013-07-14', '2018-06-22'),
    (5, 'Mateo Romero', 'Ourense', '2013-05-30', '2018-06-22'),
    (5, 'Lucía Pereira', 'Pontevedra', '2013-04-22', '2018-06-22'),
    (5, 'Hugo Martínez', 'Ferrol', '2013-01-09', '2018-06-22'),
    (5, 'David Díaz', 'Betanzos', '2013-11-05', '2018-06-22'),
    (5, 'María Salgado', 'Ribeira', '2013-12-30', '2018-06-22'),
    (5, 'Santi Castro', 'Vilagarcía', '2013-02-15', '2018-06-22'),
    (5, 'Mateo Álvarez', 'A Coruña', '2013-03-08', '2018-06-22'),
   	(5, 'Antía Fernández', 'A Coruña', '2013-12-19', '2018-06-22'),
       (5, 'Leo González', 'Santiago', '2013-10-05', '2018-06-22'),
       (5, 'Valeria López', 'Lugo', '2013-02-18', '2018-06-22'),
       (5, 'Xiana Romero', 'Ourense', '2013-05-09', '2018-06-22'),
       (5, 'Brais Pereira', 'Pontevedra', '2013-01-29', '2018-06-22'),
       (5, 'Noa Martínez', 'Ferrol', '2013-08-02', '2018-06-22'),
       (5, 'Javi Díaz', 'Betanzos', '2013-06-10', '2018-06-22'),
       (5, 'Dani González', 'Ribeira', '2013-09-25', '2018-06-22'),
       (5, 'Laura Salgado', 'Vilagarcía', '2013-04-30', '2018-06-22'),
       (5, 'Santi Castro', 'A Coruña', '2013-11-01', '2018-06-22'),
       (5, 'Adrián Álvarez', 'Santiago', '2013-12-14', '2018-06-22'),
       (6, 'Paula Fernández', 'A Coruña', '2012-04-25', NULL),
       (6, 'Adrián Rodríguez', 'Santiago', '2012-05-30', NULL),
       (6, 'Marta López', 'Lugo', '2012-01-12', NULL),
       (6, 'Antón Pérez', 'Ourense', '2012-06-02', NULL),
       (6, 'Hugo Gómez', 'Pontevedra', '2012-10-10', NULL),
       (6, 'Iago Martínez', 'Ferrol', '2012-07-19', NULL),
       (6, 'Carla Castro', 'Betanzos', '2012-03-05', NULL),
       (6, 'Xoán Torres', 'Ribeira', '2012-11-08', NULL),
       (6, 'Martín Álvarez', 'Vilagarcía', '2012-09-15', NULL),
       (6, 'Valeria Fernández', 'A Coruña', '2012-12-18', NULL),
       (6, 'Leo González', 'Santiago', '2012-08-27', NULL),
       (6, 'Noa López', 'Lugo', '2012-02-29', NULL),
       (6, 'Javi Romero', 'Ourense', '2012-03-14', NULL),
       (6, 'Brais Pereira', 'Pontevedra', '2012-01-21', NULL),
       (6, 'Sara Martínez', 'Ferrol', '2012-05-22', NULL),
       (6, 'Antía Díaz', 'Betanzos', '2012-11-30', NULL),
       (6, 'Dani González', 'Ribeira', '2012-06-15', NULL),
       (6, 'Laura Salgado', 'Vilagarcía', '2012-08-01', NULL),
       (6, 'Mateo Castro', 'A Coruña', '2012-04-08', NULL),
       (6, 'Xiana Álvarez', 'Santiago', '2012-10-11', NULL),
       (7, 'Andrés Fernández', 'A Coruña', '2011-04-19', NULL),
       (7, 'Carla Rodríguez', 'Santiago', '2011-05-21', NULL),
       (7, 'Brais López', 'Lugo', '2011-01-11', NULL),
       (7, 'Paula Pérez', 'Ourense', '2011-06-04', NULL),
       (7, 'Hugo Gómez', 'Pontevedra', '2011-11-06', NULL),
       (7, 'Sara Martínez', 'Ferrol', '2011-03-16', NULL),
       (7, 'Iago Castro', 'Betanzos', '2011-09-01', NULL),
       (7, 'Xoán Torres', 'Ribeira', '2011-12-25', NULL),
       (7, 'Antía Álvarez', 'Vilagarcía', '2011-08-20', NULL),
       (7, 'Mateo Fernández', 'A Coruña', '2011-07-02', NULL),
       (7, 'Laura González', 'Santiago', '2011-10-15', NULL),
       (7, 'Noa López', 'Lugo', '2011-02-10', NULL),
       (7, 'Martín Romero', 'Ourense', '2011-01-23', NULL),
       (7, 'Valeria Pereira', 'Pontevedra', '2011-06-13', NULL),
       (7, 'Adrián Martínez', 'Ferrol', '2011-05-30', NULL),
       (7, 'Javi Díaz', 'Betanzos', '2011-03-14', NULL),
       (7, 'Xiana González', 'Ribeira', '2011-04-08', NULL),
       (7, 'Dani Salgado', 'Vilagarcía', '2011-12-20', NULL),
       (7, 'Hugo Castro', 'A Coruña', '2011-11-18', NULL),
       (7, 'Carla Álvarez', 'Santiago', '2011-02-22', NULL),
       (8, 'Iván Fernández', 'A Coruña', '2010-04-10', NULL),
       (8, 'Marta Rodríguez', 'Santiago', '2010-05-25', NULL),
       (8, 'Brais López', 'Lugo', '2010-01-30', NULL),
       (8, 'Valeria Pérez', 'Ourense', '2010-06-12', NULL),
       (8, 'Inés Gómez', 'Pontevedra', '2010-11-22', NULL),
       (8, 'Hugo Martínez', 'Ferrol', '2010-03-15', NULL),
       (8, 'Iago Castro', 'Betanzos', '2010-08-19', NULL),
       (8, 'Carla Torres', 'Ribeira', '2010-09-02', NULL),
       (8, 'Antía Álvarez', 'Vilagarcía', '2010-12-03', NULL),
       (8, 'Mateo Fernández', 'A Coruña', '2010-07-14', NULL),
       (8, 'Noa González', 'Santiago', '2010-02-17', NULL),
       (8, 'Adrián López', 'Lugo', '2010-01-12', NULL),
       (8, 'Xiana Romero', 'Ourense', '2010-03-29', NULL),
       (8, 'Sara Pereira', 'Pontevedra', '2010-08-21', NULL),
       (8, 'Martín Martínez', 'Ferrol', '2010-04-18', NULL),
       (8, 'Javi Díaz', 'Betanzos', '2010-05-11', NULL),
       (8, 'Laura González', 'Ribeira', '2010-06-25', NULL),
       (8, 'Hugo Salgado', 'Vilagarcía', '2010-09-30', NULL),
       (8, 'Carla Castro', 'A Coruña', '2010-02-01', NULL),
       (8, 'Iván Álvarez', 'Santiago', '2010-11-15', NULL),
       (9, 'Alba Fernández', 'A Coruña', '2009-05-25', '2018-06-30'),
		(9, 'Javi Rodríguez', 'Santiago', '2009-01-30', '2018-06-30'),
		(9, 'Inés López', 'Lugo', '2009-06-12', '2018-06-30'),
		(9, 'Hugo Pérez', 'Ourense', '2009-07-04', '2018-06-30'),
		(9, 'Carla Gómez', 'Pontevedra', '2009-08-21', '2018-06-30'),
		(9, 'Adrián Martínez', 'Ferrol', '2009-09-10', '2018-06-30'),
		(9, 'Iago Castro', 'Betanzos', '2009-02-01', '2018-06-30'),
		(9, 'Antía Torres', 'Ribeira', '2009-10-15', '2018-06-30'),
		(9, 'Valeria Álvarez', 'Vilagarcía', '2009-03-18', '2018-06-30'),
		(9, 'Mateo Fernández', 'A Coruña', '2009-11-20', '2018-06-30'),
		(9, 'Sara González', 'Santiago', '2009-12-30', '2018-06-30'),
		(9, 'Noa López', 'Lugo', '2009-04-25', '2018-06-30'),
		(9, 'Brais Romero', 'Ourense', '2009-08-13', '2018-06-30'),
		(9, 'Xiana Salgado', 'Pontevedra', '2009-07-29', '2018-06-30'),
		(9, 'Javi Martínez', 'Ferrol', '2009-06-15', '2018-06-30'),
		(9, 'Hugo Díaz', 'Betanzos', '2009-09-30', '2018-06-30'),
		(9, 'Laura González', 'Ribeira', '2009-02-28', '2018-06-30'),
		(9, 'Antón Castro', 'Vilagarcía', '2009-05-02', '2018-06-30'),
		(9, 'Dani Álvarez', 'A Coruña', '2009-12-15', '2018-06-30'),
       (10, 'Brais Fernández', 'A Coruña', '2008-01-21', NULL),
       (10, 'Antía Rodríguez', 'Santiago', '2008-04-12', NULL),
       (10, 'Paula López', 'Lugo', '2008-05-05', NULL),
       (10, 'Inés Pérez', 'Ourense', '2008-11-16', NULL),
       (10, 'Javi Gómez', 'Pontevedra', '2008-09-02', NULL),
       (10, 'Santi Martínez', 'Ferrol', '2008-06-08', NULL),
       (10, 'Laura Castro', 'Betanzos', '2008-10-20', NULL),
       (10, 'Xoán Torres', 'Ribeira', '2008-07-03', NULL),
       (10, 'Adrián Álvarez', 'Vilagarcía', '2008-08-29', NULL),
       (10, 'Valeria Fernández', 'A Coruña', '2008-12-04', NULL),
       (10, 'Hugo González', 'Santiago', '2008-03-14', NULL),
       (10, 'Noa López', 'Lugo', '2008-02-18', NULL),
       (10, 'Sara Romero', 'Ourense', '2008-01-01', NULL),
       (10, 'Mateo Pereira', 'Pontevedra', '2008-07-15', NULL),
       (10, 'Xiana Martínez', 'Ferrol', '2008-05-30', NULL),
       (10, 'Dani Díaz', 'Betanzos', '2008-11-27', NULL),
       (10, 'Martín Salgado', 'Ribeira', '2008-10-19', NULL),
       (10, 'Carla Castro', 'Vilagarcía', '2008-06-22', NULL),
       (10, 'Iván Álvarez', 'A Coruña', '2008-09-10', NULL),
       (10, 'Javier Salgado', 'A Coruña', '2008-03-13', NULL),
       (11, 'Noa Fernández', 'A Coruña', '2007-01-12', '2018-05-20'),
		(11, 'Iago Rodríguez', 'Santiago', '2007-02-24', '2018-05-20'),
		(11, 'Carla López', 'Lugo', '2007-03-18', '2018-05-20'),
		(11, 'Adrián Pérez', 'Ourense', '2007-04-09', '2018-05-20'),
		(11, 'Inés Gómez', 'Pontevedra', '2007-05-16', '2018-05-20'),
		(11, 'Hugo Martínez', 'Ferrol', '2007-06-30', '2018-05-20'),
		(11, 'Valeria Castro', 'Betanzos', '2007-07-05', '2018-05-20'),
		(11, 'Brais Torres', 'Ribeira', '2007-08-19', '2018-05-20'),
		(11, 'Sara Álvarez', 'Vilagarcía', '2007-09-15', '2018-05-20'),
		(11, 'Martín Fernández', 'A Coruña', '2007-10-22', '2018-05-20'),
		(11, 'Xiana González', 'Santiago', '2007-11-11', '2018-05-20'),
		(11, 'Javi Romero', 'Lugo', '2007-12-01', '2018-05-20'),
		(11, 'Laura Pereira', 'Ourense', '2007-01-30', '2018-05-20'),
		(11, 'Antía Salgado', 'Pontevedra', '2007-02-14', '2018-05-20'),
		(11, 'Mateo Martínez', 'Ferrol', '2007-03-26', '2018-05-20'),
		(11, 'Javi Díaz', 'Betanzos', '2007-04-03', '2018-05-20'),
		(11, 'Carla González', 'Ribeira', '2007-05-10', '2018-05-20'),
		(11, 'Iván Castro', 'Vilagarcía', '2007-06-18', '2018-05-20'),
		(11, 'Noa Álvarez', 'A Coruña', '2007-07-12', '2018-05-20'),
		(11, 'Adrián Fernández', 'Santiago', '2007-08-30', '2018-05-20')
;



--Datos tabla PROFESOR
INSERT INTO PUBLIC.PUBLIC.PROFESOR (NOMBRE, FECHA_NACIMIENTO, FECHA_MUERTE) VALUES
	('Carlos García Vázquez', '1950-04-15', NULL),
	('Lucía Martínez Rodríguez', '1965-07-10', NULL),
	('José Fernández Castro', '1972-09-25', '2022-06-15'),
	('María López Pérez', '1980-11-30', NULL),
	('Manuel Sánchez González', '1958-01-22', NULL),
	('Ana Ruiz Barreiro', '1975-08-19', NULL), 
	('Francisco Jiménez López', '1960-02-13', '2020-09-20'),
	('Laura Gómez Freire', '1983-05-24', NULL),
	('Antonio Díaz Martínez', '1945-10-03', '2015-12-05'),
	('Elena Morales Souto', '1990-03-08', NULL), 
	('Pedro Ortega López', '1968-06-17', NULL),
	('Isabel Castro González', '1953-09-12', NULL),
	('Miguel Vázquez Otero', '1970-12-28', '2019-02-11'), 
	('Clara Navarro Fernández', '1987-07-14', NULL),
	('David Romero López', '1992-04-27', NULL),
	('Raquel Pérez González', '1962-05-19', NULL),
	('Luis Torres Fernández', '1978-11-05', NULL),
	('Sofía Castillo Rodríguez', '1985-01-17', NULL),
	('Javier Muñoz Piñeiro', '1948-06-29', NULL), 
	('Marta Herrera López', '1955-02-14', NULL)
;



--Datos tabla ASIGNATURA	
INSERT INTO PUBLIC.PUBLIC.ASIGNATURA (ID_CURSO, ID_PROFESOR, NOMBRE) VALUES
    (0, 2, 'MATEMÁTICAS'),
    (0, 4, 'NATURALES'),
    (0, 1, 'LENGUA_ESPAÑOLA'),
    (0, 6, 'LINGUA_GALEGA'),
    (1, 3, 'MATEMÁTICAS'),
    (1, 8, 'NATURALES'),
    (1, 5, 'LENGUA_ESPAÑOLA'),
    (1, 4, 'LINGUA_GALEGA'),
    (2, 7, 'MATEMÁTICAS'),
    (2, 2, 'NATURALES'),
    (2, 9, 'LENGUA_ESPAÑOLA'),
    (2, 3, 'LINGUA_GALEGA'),
    (3, 5, 'MATEMÁTICAS'),
    (3, 1, 'NATURALES'),
    (3, 6, 'LENGUA_ESPAÑOLA'),
    (3, 8, 'LINGUA_GALEGA'),
    (4, 0, 'MATEMÁTICAS'),
    (4, 7, 'NATURALES'),
    (4, 3, 'LENGUA_ESPAÑOLA'),
    (4, 2, 'LINGUA_GALEGA'),
    (5, 4, 'MATEMÁTICAS'),
    (5, 9, 'NATURALES'),
    (5, 0, 'LENGUA_ESPAÑOLA'),
    (5, 5, 'LINGUA_GALEGA'),
    (6, 10, 'BIOLOGÍA'),
    (6, 12, 'HISTORIA'),
    (6, 15, 'GEOGRAFÍA'),
    (6, 11, 'FÍSICA_QUÍMICA'),
    (6, 14, 'INGLÉS'),
    (7, 13, 'BIOLOGÍA'),
    (7, 10, 'HISTORIA'),
    (7, 18, 'GEOGRAFÍA'),
    (7, 16, 'FÍSICA_QUÍMICA'),
    (7, 12, 'INGLÉS'),
    (8, 19, 'BIOLOGÍA'),
    (8, 17, 'HISTORIA'),
    (8, 10, 'GEOGRAFÍA'),
    (8, 15, 'FÍSICA_QUÍMICA'),
    (8, 13, 'INGLÉS'),
    (9, 11, 'BIOLOGÍA'),
    (9, 16, 'HISTORIA'),
    (9, 14, 'GEOGRAFÍA'),
    (9, 10, 'FÍSICA_QUÍMICA'),
    (9, 18, 'INGLÉS'),
    (10, 2, 'HISTORIA_ARTE'),
    (10, 5, 'ECONOMÍA'),
    (10, 8, 'LATÍN'),
    (10, 12, 'QUÍMICA'),
    (10, 7, 'FILOSOFÍA'),
    (11, 1, 'HISTORIA_ARTE'),
    (11, 3, 'ECONOMÍA'),
    (11, 6, 'LATÍN'),
    (11, 10, 'QUÍMICA'),
    (11, 9, 'FILOSOFÍA')
  ;
 
 --Datos tabla CURSO_ASIGNATURA
INSERT INTO PUBLIC.PUBLIC.CURSO_ASIGNATURA (ID_CURSO, ID_ASIGNATURA) VALUES
	(0, 0),
	(0, 1),
	(0, 2),
	(0, 3),
	(1, 4),
	(1, 5),
	(1, 6),
	(1, 7),
	(2, 8),
	(2, 9),
	(2, 10),
	(2, 11),
	(3, 12),
	(3, 13),
	(3, 14),
	(3, 15),
	(4, 16),
	(4, 17),
	(4, 18),
	(4, 19),
	(5, 20),
	(5, 21),
	(5, 22),
	(5, 23),
	(6, 24),
	(6, 25),
	(6, 26),
	(6, 27),
	(6, 28),
	(7, 29),
	(7, 30),
	(7, 31),
	(7, 32),
	(7, 33),
	(8, 34),
	(8, 35),
	(8, 36),
	(8, 37),
	(8, 38),
	(9, 39),
	(9, 40),
	(9, 41),
	(9, 42),
	(9, 43),
	(10, 44),
	(10, 45),
	(10, 46),
	(10, 47),
	(10, 48),
	(11, 49),
	(11, 50),
	(11, 51),
	(11, 52),
	(11, 53)
;
 


/*-----------------------------------------------------------------------------------------
										CONSULTAS
-----------------------------------------------------------------------------------------*/


/*---------------------------------
			 FÁCILES
 --------------------------------*/

--1-Dime todos los profesores que se apelliden Pérez y que tengan mas 50 años de edad

SELECT
	p.NOMBRE, DATEDIFF('YEAR',
	p.FECHA_NACIMIENTO,
	TODAY()) AS EDAD_PROFESOR	
FROM
	PUBLIC.PUBLIC.PROFESOR p
WHERE
	p.NOMBRE LIKE '%Pérez%' AND
	DATEDIFF('YEAR',
	p.FECHA_NACIMIENTO,
	TODAY()) > 50
;



--2-Sacar la edad media de los estudiantes que se hayan graduado

        
--3-Dime todos los profesores que hayan muerto en el mes de junio

          
--4-Dime cuales son las 3 ultimas asignaturas que se registraron

            
           
/*---------------------------------
			MEDIANAS
---------------------------------*/
           
--5--Lista los profesores imparten más de dos asignatura he indica cuantas son

SELECT
	p.NOMBRE,
	COUNT(a.ID_PROFESOR) AS CUANTAS
FROM
	PUBLIC.PUBLIC.ASIGNATURA a
INNER JOIN PUBLIC.PUBLIC.PROFESOR p ON
	a.ID_PROFESOR = p.ID_PROFESOR
	--WHERE COUNT(a.ID_PROFESOR) > 2 NO FUNCIONA Y NO HAY MANERA DE QUE LO HAGA
GROUP BY
	p.NOMBRE
ORDER BY
	COUNT(a.ID_PROFESOR) DESC;          


--6--¿Qué cursos se imparten en cada escuela?


--7--Obtener el nombre de alumnos por curso y ordenarlo de mayor a menor edad:


--8--Muestrame el numero de asignaturas por curso



/*---------------------------------
			DIFÍCILES
---------------------------------*/

--9--Dime el numero de aula/s en la que le imparten clase a los niños de primaria de primer curso

SELECT COUNT(DISTINCT a.ID_AULA)
FROM PUBLIC.PUBLIC.AULA a
INNER JOIN PUBLIC.PUBLIC.CURSO c ON a.ID_CURSO = c.ID_CURSO
INNER JOIN PUBLIC.PUBLIC.ALUMNO a2 ON c.ID_CURSO = a2.ID_CURSO 
WHERE c.NOMBRE LIKE 'PRIMERO_PRIMARIA';


--10--Obtener la lista de alumnos y sus profesores respectivos (a través de las asignaturas que cursan)


--11--Indica cuantas asignaturas se imparten en cada escuela


--12--Dime el profesor que imparta la asignatura "LINGUA_GALEGA" y el número de alumnos a los que imparte clase que residan en Coruña del curso de sexto de primaria, de la escuela que tenga direccion en Coruña.
   











